### ISSUE TITLE
July 2023 Contributions - {rafaccc#5473}

### ISSUE THREAD

**Issue by rafaccc** [Phala-Network/growth-program#238]
Telegram : [rafaccc](https://t.me/rafaccc)
Discord : rafaccc#5473
Dirección PHA: 42LYD29z2f6hYQeuamH5puXTGa1KHhWd6YxYSHXzRjih4xJd

On Twitter, Telegram and Discord I promoted Phala Network and PhatContract.
I also answered questions from the community.

**Telegram**
![image](https://github.com/Phala-Network/growth-program/assets/97988345/e7bf576d-00fd-435e-9fd8-2b998fecb29a)
![image](https://github.com/Phala-Network/growth-program/assets/97988345/b41084c4-7a6c-4920-8ced-afca0c41966a)

**Twitter**
![image](https://github.com/Phala-Network/growth-program/assets/97988345/1bde1ca0-d00c-410e-9563-bc4cfee4bfcb)
![image](https://github.com/Phala-Network/growth-program/assets/97988345/c7c689bc-fbf5-431c-9931-ce3f0669a11d)
![image](https://github.com/Phala-Network/growth-program/assets/97988345/799bb388-dcb5-4aaf-afb8-2b942e360638)

**Article translation**
https://medium.com/@rafacabilla/bolet%C3%ADn-mensual-de-phala-junio-2023-fc6086213a00?postPublishedType=initial

**ART: Some images created by me**
![image](https://github.com/Phala-Network/growth-program/assets/97988345/b5068764-5f5d-40a6-ad92-804fd9638039)

**Gif thread:**
https://twitter.com/RafaelCabilla/status/1683241448466989056
![image](https://github.com/Phala-Network/growth-program/assets/97988345/635ad618-be51-45e4-9d03-73c23ee3551a)

**Gif /movie:**
https://twitter.com/RafaelCabilla/status/1683985911464206342

----
CM 37
MK 37
CC 8
Art 10

**Comment by willphala** [comment]
Nice work! I've written some feedback which I hope is helpful and well received. Also it would be great if we could recruit another Spanish ambassador. Do you know of any potential good candidates? 

- ML: Please don't forget to include your marketing statistics in our team document otherwise it's hard to grade your marketing contributions accurately.

- ART: To get 10/10 please focus on producing content that Phala Network is prioritising. It would also be great to see other variations apart from GIFs. For example, I thought Chris's artwork on Lens/Phala was great - https://twitter.com/BckChris/status/1686028681141952514  

- 'Last generation technology': this should be 'first' not 'last'. Last implies that it's outdated. If you're unsure about any words in English please ask our team for support in the CC Discord channel. 

- CM: It would be great if you could share some commentary about how our local Spanish community is progressing. Providing statistics is important but I need more information for example, have we improved, regressed, what's been done to improve and move the community forward etc.

It would also be great to see some community based events like monthly community calls etc too.
