### ISSUE TITLE
August

### ISSUE THREAD

**Issue by terrencejinqu** [Phala-Network/growth-program#255]
![d2bb6ee791f7fc2355defd2107e4aec](https://github.com/Phala-Network/growth-program/assets/140965898/41ed172b-20d2-4d86-ab82-5021f0d5c9aa)

**Comment by Marvin-Cypher** [comment]
I'll help to review Chinese ambassador / contents.

- Please summit links as proof of work
   - Screenshot is optional and secondary
- Please ONLY summit the work for this month 
   - We need to check AMBs' monthly contribution based on task list. 
 
 So please edit the submission so that we can get your contribution more clear.

1. weekly report post
- Share the Wechat blog link for posted weekly progress
- Share the picture link for weekly updates

2.Blog / translation about Phala
- Share link for each blog

3. AMA
- Share link for each blog / summary

4. Dashboard for social media
- Share the metrics for this month of Wechat blog
  - New users increase
  - Total increase
  - Read engagement

...


If you want to share the privous work, plz add issues to each month of 2023
