### ISSUE TITLE
December 2022 Contributions - {Jeretucu | Tucuman.Phala#4603}

### ISSUE THREAD

**Issue by Jeretucu** [Phala-Network/growth-program#88]
Telegram : [jeretucu](https://t.me/jeretucu)
Discord : Jeretucu | Tucuman.Phala#4603
PHA Address : 41D9LFABTeEMZMgaskRaob15k6c7RAsriJeLNSnvWVApZnv3

Contributions of December : CC50% & CM50%

**CC (Content)**
Make all the translations of the weeklies in the official channel of Phala in Spanish (https://medium.com/phala-espa%C3%B1ol)
https://medium.com/phala-espa%C3%B1ol/la-app-phala-v2-0-5979a58d0604
https://medium.com/phala-espa%C3%B1ol/las-funciones-on-chain-del-stakepool-v2-se-est%C3%A1n-actualizando-phalaworld-dress-up-ya-est%C3%A1-e87772cbea94
https://medium.com/phala-espa%C3%B1ol/la-prueba-beta-de-phala-app-v2-0-d866ae9ce732
https://medium.com/phala-espa%C3%B1ol/phala-app-2-0-e837f45b7b25
https://medium.com/phala-espa%C3%B1ol/an%C3%A1lisis-t%C3%A9cnico-de-por-qu%C3%A9-phala-no-se-ve-afectado-por-vulnerabilidades-en-sgx-de-chips-intel-a21ce9ed1c74
https://medium.com/phala-espa%C3%B1ol/descubra-las-emocionantes-nuevas-funciones-de-la-app-de-phala-que-hacen-a-su-delegaci%C3%B3n-m%C3%A1s-c775e83c3a06

One of the star products of Stakepool V2 is "Vault", try to generate a lot of content about it 
I created a technical tutorial on "how to create a vault" (I shared it with other communities)
https://medium.com/@jeretucu/tutorial-como-crear-un-vault-adc9982a568d

![image](https://user-images.githubusercontent.com/107716407/210446719-e29e8c46-4677-4506-bb7b-ffd2b1813962.png)
Build a Vault and invite the community to join and create their own
![image](https://user-images.githubusercontent.com/107716407/210449543-c19d751f-9496-4fda-b618-634ae60da54b.png)

Invite the community in Spanish to participate in the testing of Stakepool V2
![image](https://user-images.githubusercontent.com/107716407/210451372-7e28d331-58c3-42ec-97a8-778549e781a1.png)

**CM (community)**
Actively participate in reporting incidents about Stakepool V2
Generating documents and videos for our developers
Example
![image](https://user-images.githubusercontent.com/107716407/210447417-ceb85b68-76a4-4b0f-b5dc-4579de6850bb.png)
![image](https://user-images.githubusercontent.com/107716407/210447552-5d6f1d17-80d5-4abc-abde-2250be6be4e5.png)
![image](https://user-images.githubusercontent.com/107716407/210447642-1c9bd4e4-0214-447e-ba2c-dfc0c3c55fbc.png)

Chat: I was active in the Spanish chat answering questions (please check Spanish telegram chat)

 ![image](https://user-images.githubusercontent.com/107716407/210445550-bdfec329-6ee5-40bf-9076-05e4a10bd2dc.png)

![image](https://user-images.githubusercontent.com/107716407/210445679-2b51f478-f4ba-4379-a3a8-84dfef4a01ba.png)

I was able to increase the visits on twitter
Twitter as Official Ambassador : https://twitter.com/jeretucu
Analytic : https://analytics.twitter.com/user/jeretucu/tweets

On my twitter I only make publications related to Phala Network

![image](https://user-images.githubusercontent.com/107716407/210450372-8569f463-00ff-4ad6-9133-22e2dd0487d5.png)
![image](https://user-images.githubusercontent.com/107716407/210450504-ec5cd355-5aef-40d9-b5c7-08d392250d50.png)

Hi Will, I hope I can reach 90%
Increase my participation a lot this month.
Community 38/40
Contect  35/40
Supplementary tasks, 20/20 (TT, CC)

**Comment by willphala** [comment]
@Jeretucu 

Departments:

1.	CC: 30/40:

•	Translated a significant number of articles, great work!
•	Good tutorial, these are very much needed so excellent initiative. 
•	I would like to see you participate more in CC discussions e.g. engaging with other ambs, providing suggestions etc.
•	You did not contribute to the department tasks. It would be great to see you contribute moving forwards.

2.	CM: 30/40:
•	Reporting incidents about V2 was crucial this month so great work. However please also record these insights, feedback, and bugs in our community digest doc.
•	Generating docs and videos for our developers is CC not CM, so I have added this to your CC score.
•	Good activity in TG. 
•	Did not initiate and barely contributed to CM discussions.
•	Good to see you trying to get the Spanish community involved in V2. 
•	Active in Discord mining/Spanish channel. 

Supplementary tasks:
•	Both TT/CC have been added to your CC score as these are department requirements. 

1.	PM: 10/10. 
•	Please record your analytics in our MK Twitter analytics doc. 
2.	BH: 10/10.

Summary:

Your contributions and performance have increased this month so great work. However I do not feel that this is reflected in your score for two reasons: 1) lack of participation in departments and 2) your selection of supplementary tasks. 

To achieve 90> you need to significantly increase your activity and contributions to your selected departments. To achieve a higher here you need to e.g. suggests/implement improvements and show leadership skills such as taking ownership of specific tasks etc. 

Additionally you cannot compound your scores by participating in e.g. the CC department and supplement this with CC related supplementary tasks. This is because the CC supplementary tasks are standard required contributions in the CC department.
