### ISSUE TITLE
December 2022 Contribution - {Angie_ada#0973}

### ISSUE THREAD

**Issue by Angie-ada** [Phala-Network/growth-program#95]
Telegram Username: @angie_ada
Discord Username: Angie_ada#0973
Twitter Username: https://twitter.com/_encrypted_____
PHA Wallet Address: 
42qf1tXPH8HfxBqUpTv79VHiTghEatoBnM1QULFgRRXeiUiL

Contributions:
DEPARTMENTAL
MK - Co-created and executed marketing strategy and content (pitch deck presentation) to reach out to indigenous developer Communities with the aim of onboarding these blockchain devs into adopting Phala's phat contract technology. Also executed an online promotional event on twitter (Meme contest). The goals of this was to increase engagement, promote community growth, product usage and brand awareness.
https://drive.google.com/file/d/1aHhsSe1RhHJnibrk8FjeuiIW4uVbp2iy/view?usp=drivesdk
Ps. I'm presenting this in a zoom meeting on Monday.

CM	Community: I participated in community moderation by nurturing, providing support to new and inexperienced users of the updated Phala App V2 in both Local and global Phala communities. 
The Nigerian Community had a temporary issue from telegram, this was sorted as soon as possible and with the help of the meme contest and other promotional activities, we gained an additional 10 members.
![Screenshot_20230107-004501](https://user-images.githubusercontent.com/87555884/211161779-065cfbd2-9e5b-4592-8117-3c8852164243.png)
]

SUPPLEMENTARY
PM - Made 5 promotional threads on Twitter.
https://twitter.com/_encrypted_____/status/1611370201693519873?t=OJR1u4K4cVS_ULI_csGxdw&s=19
https://twitter.com/_encrypted_____/status/1611389770457817089?t=OJR1u4K4cVS_ULI_csGxdw&s=19
https://twitter.com/_encrypted_____/status/1611408060358037504?t=OJR1u4K4cVS_ULI_csGxdw&s=19
https://twitter.com/_encrypted_____/status/1611487992119545882?t=OJR1u4K4cVS_ULI_csGxdw&s=19
https://twitter.com/_encrypted_____/status/1611499555052490752?t=OJR1u4K4cVS_ULI_csGxdw&s=19
Stats;
![Screenshot_20230107-184245](https://user-images.githubusercontent.com/87555884/211163605-f355a1a0-9e5c-46e5-a68b-c860c3de4781.png)
![Screenshot_20230107-184228](https://user-images.githubusercontent.com/87555884/211163611-78a2da84-86ef-47d1-9f29-74947087c3c3.png)
![Screenshot_20230107-184214](https://user-images.githubusercontent.com/87555884/211163617-b94e6dfb-63da-4a09-b664-7504d7efd66c.png)
![Screenshot_20230107-184147](https://user-images.githubusercontent.com/87555884/211163625-21ccef9d-55d4-47b4-9012-3bbb0dcf6fa4.png)
![Screenshot_20230107-183822](https://user-images.githubusercontent.com/87555884/211163632-3c4a44d0-fec1-4b73-b3ea-96d454eee3dc.png)

 

TT - Wrote a tutorial on delegating PHA in Vault.
  https://link.medium.com/H9BH2mQ1mwb
![Screenshot_20230107-181307](https://user-images.githubusercontent.com/87555884/211162518-c504bfce-743e-4f35-900d-67a876361d42.png)

RC - created awareness about the ambassador programme, within the global and Nigerian communities and Twitter.
Not sure about the precise number of applications that were sent.

Summary;
- Suggested supplementary  scores 
Pm- 10%, TT- 10%
- Suggested scores for selected departments 45/45 (Marketing) and 28/35 (Community) 
- 80% Department score weight:-
- 45% for MK and 
- 35% for CM. 
- TOTAL SUGGESTED SCORE 10+10+45+28=88%

**Comment by willphala** [comment]
@Angie-ada 

Departments:

1.	MK: 25/45:

•	Excellent initiative with the pitchdeck. It would be great to have some info about the results though?
•	Competitions are always fun so it’s great to hear you did one. However, again, it would be good to hear about the outcome/results? 
•	You have not provided me with your Twitter analytics in either attached screenshots or our MK doc (which is mandatory). Unfortunately this prevents me from giving you an accurate score. 
•	You’ve been fairly active in the MK channel which is good but there is room for improve here.
•	Did not contribute to MK Outbound account list doc.
•	Promoted the amb programme which was great to see. Keep it up!

2.	CM: 26/35:

•	Good Combot stats. 
•	You’ve been fairly active in the CM channel which is good but there is room for improve here.
•	Co-managing a sub community which is important. I would like to hear some feedback/updates though. 
•	Did not record any community insights, questions, product feedback etc in our CM Community Digest doc. This is very important work for the CM department. 

Supplementary tasks:
•	PM/RC is included in your MK score, as they are MK department tasks. 

1.	TT: 10/10. 

Summary:

Good work. However I do not feel that this is reflected in your score for 3 reasons: 1) lack of participation in departments and 2) your selection of supplementary tasks 3) A lack of information in this report. 

To achieve a higher score you need to significantly increase your activity and contributions to your selected departments. To achieve a higher here you need to e.g. suggests/implement improvements and show leadership skills such as taking ownership of specific tasks etc.

Additionally you cannot compound your scores by participating in e.g. the MK department and supplement this with MK related supplementary tasks (PM/RC). This is because the MK supplementary tasks are standard required contributions in the MK department.
